version: '3.8'

services:
  calculator:
    image: calculator:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./api/swagger:/api/swagger
    environment:
      - ENVIRONMENT=production